// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CharactersConfirmRemove: typeof import('./components/characters/confirm-remove.vue')['default']
    ElementsForm: typeof import('./components/elements-form.vue')['default']
    'IconCarbon:chevronDown': typeof import('~icons/carbon/chevron-down')['default']
    'IconCarbon:chevronUp': typeof import('~icons/carbon/chevron-up')['default']
    'IconDashicons:menuAlt3': typeof import('~icons/dashicons/menu-alt3')['default']
    'IconFaSolid:handSparkles': typeof import('~icons/fa-solid/hand-sparkles')['default']
    'IconIc:baselineHealthAndSafety': typeof import('~icons/ic/baseline-health-and-safety')['default']
    'IconIconoir:gym': typeof import('~icons/iconoir/gym')['default']
    'IconMdi:runFast': typeof import('~icons/mdi/run-fast')['default']
    'IconPandoraGateRpgHelper:agility': typeof import('~icons/pandora-gate-rpg-helper/agility')['default']
    'IconPandoraGateRpgHelper:dexterity': typeof import('~icons/pandora-gate-rpg-helper/dexterity')['default']
    'IconPandoraGateRpgHelper:luck': typeof import('~icons/pandora-gate-rpg-helper/luck')['default']
    'IconPandoraGateRpgHelper:pandoraGate': typeof import('~icons/pandora-gate-rpg-helper/pandora-gate')['default']
    'IconPandoraGateRpgHelper:spirit': typeof import('~icons/pandora-gate-rpg-helper/spirit')['default']
    'IconPandoraGateRpgHelper:strength': typeof import('~icons/pandora-gate-rpg-helper/strength')['default']
    'IconPandoraGateRpgHelper:vitality': typeof import('~icons/pandora-gate-rpg-helper/vitality')['default']
    'IconRi:loginBoxLine': typeof import('~icons/ri/login-box-line')['default']
    'IconRi:logoutBoxLine': typeof import('~icons/ri/logout-box-line')['default']
    'IconRi:mentalHealthLine': typeof import('~icons/ri/mental-health-line')['default']
    'IconTabler:clover': typeof import('~icons/tabler/clover')['default']
    LocationForm: typeof import('./components/location-form.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
  }
}

export { }
