// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElementsForm: typeof import('./components/elements-form.vue')['default']
    'IconAkarIcons:circleX': typeof import('~icons/akar-icons/circle-x')['default']
    'IconCarbon:image': typeof import('~icons/carbon/image')['default']
    'IconCarbon:save': typeof import('~icons/carbon/save')['default']
    'IconCarbon:trashCan': typeof import('~icons/carbon/trash-can')['default']
    'IconDashicons:menuAlt3': typeof import('~icons/dashicons/menu-alt3')['default']
    'IconEosIcons:loading': typeof import('~icons/eos-icons/loading')['default']
    'IconPandoraGateRpgHelper:pandoraGate': typeof import('~icons/pandora-gate-rpg-helper/pandora-gate')['default']
    'IconRi:loginBoxLine': typeof import('~icons/ri/login-box-line')['default']
    'IconRi:logoutBoxLine': typeof import('~icons/ri/logout-box-line')['default']
    LocationForm: typeof import('./components/location-form.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
  }
}

export { }
